### ISSUE TITLE
Funding for CC: Share a template for a typical budget?

### ISSUE THREAD

**Issue by elletjies** [CarpentryConnect/carpentryconnect.org#10]
Could we share a budget template for organisations hoping to organise a CC? This might help with a funding application.

**Comment by acrall** [comment]
I really like this idea and think it would be useful to have more than one available, low to high cost dependent on budget and need. It may just be a matter of collecting generic versions from past events and continuing to modify as new events are held

**Comment by elletjies** [comment]
Created the following 2 PR's:
https://github.com/CarpentryConnect/carpentryconnect.org/pull/24
https://github.com/CarpentryConnect/carpentryconnect.org/pull/25
