### ISSUE TITLE
Decision tree images difficult to read

### ISSUE THREAD

**Issue by acrall** [CarpentryConnect/carpentryconnect.org#14]
The two decision tree images provided on [the home page](https://carpentryconnect.org/) of the planning kit are difficult to read. At a minimum, instructions need to be added to let the reader know that the image can be opened in a new tab to make it easier to see.

**Comment by elletjies** [comment]
@OscarSiba what can we do here to make it more legible?

**Comment by OscarSiba** [comment]
Wait. @elletjies so we can open it on a new tab and it become eligible! So perhaps we need to add a caption description as suggested by Alycia, stating that the image can be opened in a new tab to make it easier to read?

**Comment by elletjies** [comment]
Ok let me add that

**Comment by elletjies** [comment]
https://github.com/CarpentryConnect/carpentryconnect.org/pull/40
