### ISSUE TITLE
Add detailed alt text to decision tree images

### ISSUE THREAD

**Issue by acrall** [CarpentryConnect/carpentryconnect.org#15]
There are two detailed diagrams on [the home page](https://carpentryconnect.org/) of the planning kit. currently, the alt text provided for the images is not very descriptive so would not provide the details required to understand the diagram. Needs updating

**Comment by maneesha** [comment]
Even not considering alt text, the text in the diagrams is very difficult (near impossible) to read.

**Comment by elletjies** [comment]
https://github.com/CarpentryConnect/carpentryconnect.org/pull/21

**Comment by acrall** [comment]
Tagging @brynnelliott

**Comment by OscarSiba** [comment]
> @OscarSiba is there another way we can present this info to make it more legible?

Do we by any chance know where the original graphic is @elletjies?

**Comment by elletjies** [comment]
@OscarSiba you can find it here: https://github.com/CarpentryConnect/carpentryconnect.org/tree/master/img
