### ISSUE TITLE
Update Case Studies

### ISSUE THREAD

**Issue by elletjies** [CarpentryConnect/carpentryconnect.org#28]
@acrall I would like to update the case studies page https://carpentryconnect.org/case-studies/. Can you share the links to the other CarpentryConnect pages you know of?

**Comment by acrall** [comment]
There have only been two since I started (that I am aware of)
- [2023 New Zealand](https://www.eresearchnz2023.org.nz/carpentry-connect/)
- [2021 NZ/AU](https://www.nesi.org.nz/news/2021/02/highlights-carpentry-connect-2021-bringing-together-new-zealands-digital-skills)

**Comment by elletjies** [comment]
https://github.com/CarpentryConnect/carpentryconnect.org/pull/30
