### ISSUE TITLE
Time Keepers: URL of a suggested online countdown timer service 

### ISSUE THREAD

**Issue by naoe-tatara** [CarpentryConnect/carpentryconnect.org#4]
Thank you for the excellent work here!
I wonder if "cuckoo.com" in https://carpentryconnect.org/online/#TimeKeepers is a correct address, because the URL does not show anything. Instead, I found "cuckoo.team", which looks a correct one. 
Great if you could take a look, thank you.

**Comment by serahrono** [comment]
thanks Naoe, now fixed by https://github.com/CarpentryConnect/carpentryconnect.org/commit/5710dc4e863c3f9b76c9638d6f03b6e022f91734
