### ISSUE TITLE
Update contact for Director of Community

### ISSUE THREAD

**Issue by maneesha** [CarpentryConnect/carpentryconnect.org#41]
In the [Start Here!](https://carpentryconnect.org/in-person/#IjusthadanideatobringpeopletogetherinaCarpentryConnect) section we recommend scheduling time with the Director of Community.  This should be updated to fit our new workflows.

Assigning to @elletjies  (please feel free to re-assign if it should be someone else)

**Comment by elletjies** [comment]
@maneesha thanks, I made the update to the online and in-person pages.
