### ISSUE TITLE
Organising Committee - Access to communications platforms

### ISSUE THREAD

**Issue by elletjies** [CarpentryConnect/carpentryconnect.org#7]
Ensure all organising committee members have access to the communications platform. Also how the correspondence will be dealt with.

**Comment by acrall** [comment]
Revisit with Accessibility Coordinator once hired about this topic. Some subcommunities may require use of our infrastructure if they do not have their own

**Comment by acrall** [comment]
Tagging @brynnelliott. Happy to provide more context if needed at our next meeting
