### ISSUE TITLE
Access to certificates for CarpentryConnect attendees

### ISSUE THREAD

**Issue by elletjies** [CarpentryConnect/carpentryconnect.org#8]
Could we possibly link to the Certificates Repo here for organising committees to use? Would it be possible to customise the text in the certificate?

**Comment by acrall** [comment]
I love this idea and is something we could potentially provide for learners in workshops as well.

**Comment by elletjies** [comment]
@acrall instructors can send out certificates via this repo https://github.com/carpentries/learner-certificates

**Comment by elletjies** [comment]
@fmichonneau and @maneesha could we customise the certificates for attendees of a CarpentyConnect?

**Comment by maneesha** [comment]
I think in another context @fmichonneau  had said customizing certificates could get tricky.  Is that right?

**Comment by fmichonneau** [comment]
this type of one-off certificate would be easy to generate. The hardest part would be to design it.

**Comment by elletjies** [comment]
I have created two PR's adding information on our certificates repository
- https://github.com/CarpentryConnect/carpentryconnect.org/pull/22
- https://github.com/CarpentryConnect/carpentryconnect.org/pull/23
